### ISSUE TITLE
cursor disappears while watching demos

### ISSUE THREAD

**Issue by Rensing1** [ValveSoftware/csgo-demoinfo#27]
Hello,
when I watch a demo in csgo and want to open the demoui with shift+f2, the mouse cursor sometimes doesn't shop up. And even if it does, sometimes it only appears when the cursor is directly on the ui and sometimes it does only appear if I press esc.
Could you fix it in a way, that the cursor is always shown if the demoui is opened?
Kind regards

**Comment by kisak-valve** [comment]
Hello @Rensing1, this issue is already being tracked in various csgo-osx-linux issue reports such as https://github.com/ValveSoftware/csgo-osx-linux/issues/74, https://github.com/ValveSoftware/csgo-osx-linux/issues/294, and https://github.com/ValveSoftware/csgo-osx-linux/issues/359.

Issues with the CS:GO client should be in that issue tracker as this issue tracker is for a demo parsing utility. Closing in favor of the existing issue reports.
